name: Java CI with Maven and Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  checks: write
  pull-requests: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 17, 21]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run tests with coverage
      run: mvn clean test jacoco:report

    - name: Generate test reports
      run: mvn surefire-report:report
      if: always()

    - name: Upload JaCoCo coverage to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.java-version == '11'
      with:
        file: ./target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      if: github.event_name == 'pull_request' && matrix.java-version == '11'
      with:
        paths: |
          ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 80
        min-coverage-changed-files: 75
        title: Code Coverage Report
        update-comment: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-java-${{ matrix.java-version }}
        path: |
          target/surefire-reports/
          target/site/jacoco/
          target/site/surefire-report.html

    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests (Java ${{ matrix.java-version }})
        path: target/surefire-reports/TEST-*.xml
        reporter: java-junit
        fail-on-error: true

  coverage-check:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run coverage check
      run: |
        mvn clean test jacoco:report jacoco:check
        echo "Coverage thresholds enforced: 80% line coverage, 75% branch coverage"

    - name: Generate coverage badge
      uses: cicirello/jacoco-badge-generator@v2
      if: github.ref == 'refs/heads/main'
      with:
        generate-branches-badge: true
        jacoco-csv-file: target/site/jacoco/jacoco.csv

    - name: Comment coverage summary
      uses: 5monkeys/cobertura-action@master
      if: github.event_name == 'pull_request'
      with:
        path: target/site/jacoco/jacoco.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 80
        fail_below_threshold: true
        show_missing: true
        show_class_names: true
        only_changed_files: false
